// src/app.ts
import { Elysia } from "elysia";
import { cors } from "@elysiajs/cors";
import { staticPlugin } from "@elysiajs/static";
import { swagger } from "@elysiajs/swagger";

// Routes import
import authRoutes from "./routes/auth.routes";
import userRoutes from "./routes/user.routes";
import storeRoutes from "./routes/store/createstore.routes";
import storeCarouselRoutes from "./routes/store/store_carousel.routes";
import { ApiResponse } from "./utils/ApiResponse"; // ✅ Import ApiResponse
import storeProductRoutes from "./routes/store/store_product.routes";
import oldStoreCarouselRoutes from "./routes/store/store_carousel_old.routes";
import storeCartRoutes  from "./routes/store/store_cart.routes"
import  storeOrderRoutes  from "./routes/store/store_order.routes";
import commentRoutes from "./routes/comment.routes";
import postRoutes from "./routes/post.routes";
import deviceRoutes from "./routes/device.routes";
import favouretRoutes from "./routes/favouret.routes";
import ratingRoutes from "./routes/rating.routes";
import biddingRoutes from "./routes/bidding.routes";
import categoryRoutes from "./routes/categoury.routes";
import notificationRoutes from "./routes/notification.routes";
import { createBullBoardRoutes } from "./config/bullBoard";
import { flags } from "./config/flags";
import {
  followQueue,
  orderQueue,
  paymentQueue,
  postQueue,
  profilevisitQueue,
} from "./MQ/BullMQ/queue/notification.queue";
import {
  authEmailQueue,
  passwordEmailQueue,
  orderEmailQueue,
} from "./MQ/BullMQ/queue/email.queue";
import qstashRoutes from "./MQ/Qstash/routes";
import { clusterTracking, getClusterStats } from "./middleware/clusterTracking";
import { handleElysiaError } from "./middleware/errorHandler";

const bullBoardQueues = flags.useQstashQueue
  ? []
  : [
      followQueue(),
      orderQueue(),
      paymentQueue(),
      postQueue(),
      profilevisitQueue(),
      authEmailQueue(),
      passwordEmailQueue(),
      orderEmailQueue(),
    ];


const app = new Elysia()
  .use(clusterTracking)

  

// ✅ Global ApiResponse mapper — converts class instance to proper JSON
  .mapResponse(({ response, set }) => {
    if (response instanceof ApiResponse) {
      set.status = response.statusCode;
      return new Response(
        JSON.stringify({
          success: response.success,
          statusCode: response.statusCode,
          data: response.data,
          message: response.messege,
         
        }),
        {
          headers: { "Content-Type": "application/json" },
        }
      );
    }
  })

// ─── CORS (replaces: app.use(cors({ origin: ... }))) ─────────
  .use(
    cors({
      origin: process.env.CORS_URL || "*",
      credentials: true, // needed for cookies to work cross-origin
      allowedHeaders: ["Content-Type", "Authorization", "x-admin-token"],
      methods: ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"],
    })
  )

  // ─── Body Parsing (replaces: express.json() & express.urlencoded()) ───
  // Elysia handles JSON & form parsing AUTOMATICALLY — no middleware needed
  // But we can set body size limits:
  .onParse(({ request, contentType }) => {
    // Elysia auto-parses JSON and form data
    // Size limit is handled via maxBodySize below
  })

  // ─── Static Files (replaces: express.static('public')) ────────
  .use(
    staticPlugin({
      assets: "public",      // folder to serve
      prefix: "/",           // URL prefix
    })
  )

  // ─── Cookie Parsing ──────────────────────────────────────────
  // NO PACKAGE NEEDED — Elysia handles cookies NATIVELY
  // Access via: cookie.cookieName.value (getter)
  //             cookie.cookieName.set({ value, httpOnly, ... }) (setter)

  // ─── Swagger (replaces: setupSwagger(app)) ───────────────────
  .use(
    swagger({
      path: "/api-docs", // Swagger UI at /api-docs
      documentation: {
        info: {
          title: "API Documentation",
          version: "1.0.0",
          description: "API docs — auto-generated by Elysia Swagger",
        },
        tags: [
          { name: "Auth", description: "Authentication endpoints" },
          { name: "Users", description: "User management endpoints" },
        ],
      },
    })
  )

  // ─── Global Error Handler (replaces: app.use(errorHandler)) ──
  .onError(handleElysiaError)

  // ─── Health Check (replaces: app.use("/api/v1/healthcheck", ...)) ─
  .get("/api/v1/healthcheck", () => ({
    success: true,
    statusCode: 200,
    message: "Server is running",
    timestamp: new Date().toISOString(),
    uptime: process.uptime(),
    ...getClusterStats(),
  }))

  // ─── Mount Routes (replaces: app.use('/api/v1/users', userRouter)) ─
  .use(authRoutes)    // /api/v1/users/... (auth related)
  .use(userRoutes)
  .use(storeRoutes)
  .use(oldStoreCarouselRoutes)
  .use(storeCarouselRoutes)
  .use(storeProductRoutes)
  .use(storeCartRoutes)
  .use(storeOrderRoutes)
  .use(commentRoutes)
  .use(postRoutes)
  .use(deviceRoutes)
  .use(favouretRoutes)
  .use(ratingRoutes)
  .use(biddingRoutes)
  .use(categoryRoutes)
  .use(notificationRoutes)
  .use(createBullBoardRoutes(bullBoardQueues))
  .use(qstashRoutes)
  // ✅ Add this!
  // /api/v1/users/... (user related)

export default app;